### ISSUE TITLE
runserver 시 크롤링 커맨드를 수행할 경우 HTTP 연결 실패

### ISSUE THREAD

**Issue by gracia10** [DrugStore-devcourse/drugstore#25]
크롤링 커맨드를 runserver 시 동작하도록 구현했으나 실패했습니다.

http 연결 시도를 3회 시도하나, 모두 실패해 발생하는 이슈같습니다

현재 문제가 발생한 코드를 주석처리하였습니다 (apps/data_collection/apps.py)
```
        # FIXME HTTP 연결 실패
        # call_command('crawldata')
```

아래는 조회된 에러 문구입니다
```
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1253e33a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5c4070950b9accee3e12876b433bec1e
```

**Comment by HyeM207** [comment]
제 로컬에서 직접 실행해서 확인한 결과 동일한 WARNING이 뜨는 것을 확인했습니다.

찾아보니 WARNING 뜨는 이유는
 _urllib3 라이브러리가 HTTP 요청 실패 혹은 원격 서버가 일시적으로 사용 불가_ 일 때 발생한다고 합니다.
하지만 이는 **단순 경고**이며, 코드 실행에는 영향을 주지 않아 **로그 레벨을 조정하여 경고를 비활성화**하겠습니다.


그리고 WARNING 경고 문구 뒤에 데이터 수집될 때까지 몇 분 기다리면,
'Successful loaded crawl data.' 문구를 확인할 수 있고, db에도 잘 적재된 것을 확인하였습니다.

![image](https://user-images.githubusercontent.com/63229014/236431077-e383317c-643f-4957-9a23-aadc9bb9ebfb.png)
![image](https://user-images.githubusercontent.com/63229014/236432414-073f5b95-484b-48ff-a7ca-b9f0a0a2b89a.png)
